genres = {  'rock' : '1',
            'pop' : '2',
            'rap' : '3',
            'hip-hop' : '3',
            'easy' : '4',
            'dance' : '5',
            'house' : '5',
            'instrumental' : '6',
            'metal' : '7',
            'alternative' : '21',
            'dubstep' : '8',
            'jazz' : '1001',
            'blues' : '1001',
            'drumnbass' : '10',
            'trance' : '11',
            'chanson' : '12',
            'ethnic' : '13',
            'vocal' : '14',
            'acoustic' : '14',
            'reggae' : '15',
            'classical' : '16',
            'indie' : '17',
            'speech' : '19',
            'electropop' : '22',
            'disco' : '22',
            'other' : '18' }